import { useState } from 'react'
import marsWebp from '../assets/bodies/mars-1600.webp'
import marsPng from '../assets/bodies/mars-1600.png'
import moonWebp from '../assets/bodies/moon-1600.webp'
import moonPng from '../assets/bodies/moon-1600.png'
import { useScrollParallax } from '../hooks/useScrollParallax.js'

// Inline ~24px blurred WebP previews — instant first paint, no network round-trip (IMG-02).
// Generated by Plan 07-01; full strings live in 07-01-LQIP.md.
const LQIP = {
  mars: 'data:image/webp;base64,UklGRgIBAABXRUJQVlA4IPYAAADwBQCdASoYABgAPm0wk0ckIqGhKAqogA2JYgCpEYAXII4DaXELDLLLyGzL21eWDiaUu0Y2qB60AAD+/QPTxkulzM0QbFG66MVN8A3WyPxeg3+fpzk8wbEDv/PSyJEvMLiPhaegeaKDosIqnRtHRIT+jabpwL2VycbSX7LqXidaoiy93jX6ijQ+fapFaXfVt79O0o6+1A6UMnA5RpOAQYLjR1hC6y397z5gkMMFXO2DQ456xHjdsf5nnuypeVPS6LW++7bbnY10+Ma1mJnfoDkYuHpTwGVRUMHdUacDbsyLFRi06IpWuHL0Jvm3AWVnO3OcMggH4AA=',
  moon: 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoYABAAPm0wk0YkIyGhMAgAgA2JaQAAW+j/XnKUVYAAAP7+bmW22gMvMvUnF7XOKmVM/P6QDxbGlEnU1dXHf/gmR3TdXK4wiyUzo2dIgJ/gAA==',
}

const HERO_ASSETS = {
  mars: { webp: marsWebp, png: marsPng, alt: 'Mars — NASA image' },
  moon: { webp: moonWebp, png: moonPng, alt: 'Moon — NASA image' },
}
const BODIES = ['mars', 'moon']

// Two always-mounted body layers cross-fade via opacity (MOTION-01). Per-body loaded state
// (Pitfall 3) so each body's LQIP fades only when ITS image loads — no shared boolean.
// Parallax ref attaches to the ACTIVE inner <img> only (Pitfall 4); baseTransform keeps the
// Phase 7 translateY(-50%) center-crop (Pitfall 1). Cross-fade gated by reducedMotion (MOTION-03).
function BodyHero({ activeTab, reducedMotion }) {
  const [loaded, setLoaded] = useState({ mars: false, moon: false })
  const parallaxRef = useScrollParallax({ speed: 0.05, disabled: reducedMotion, baseTransform: 'translateY(-50%)' })

  return (
    <div className="relative w-full aspect-[16/7] rounded-lg overflow-hidden mb-4">
      {BODIES.map((body) => {
        const asset = HERO_ASSETS[body]
        const lqip = LQIP[body]
        const isActive = body === activeTab
        return (
          <div
            key={body}
            className="absolute inset-0"
            style={{ opacity: isActive ? 1 : 0, transition: reducedMotion ? 'none' : 'opacity 500ms ease' }}
          >
            {/* LQIP blur-up — image-loading concern, NOT motion: duration-300 retained regardless of reducedMotion */}
            <div
              className="absolute inset-0 bg-cover bg-center transition-opacity duration-300"
              style={{ backgroundImage: `url(${lqip})`, filter: 'blur(8px)', opacity: loaded[body] ? 0 : 1 }}
            />
            <picture>
              <source srcSet={asset.webp} type="image/webp" />
              <img
                ref={isActive ? parallaxRef : null}
                src={asset.png}
                alt={asset.alt}
                width={1600}
                height={700}
                loading="eager"
                onLoad={() => setLoaded((prev) => ({ ...prev, [body]: true }))}
                className="absolute w-full object-cover object-center"
                style={{ height: '200%', top: '50%', transform: 'translateY(-50%)', willChange: 'transform' }}
              />
            </picture>
          </div>
        )
      })}
      {/* Bottom vignette — soft handoff into the data panel below; does NOT transition */}
      <div
        className="absolute inset-x-0 bottom-0 h-1/3"
        style={{ background: 'linear-gradient(to top, #020617 0%, transparent 100%)' }}
      />
      {/* NASA image honesty label (D-01) — bottom-right dark pill; does NOT transition */}
      <span
        className="absolute bottom-2 right-2 rounded bg-black/50 px-2 py-1 text-xs text-white"
        aria-label="NASA image"
      >
        NASA image
      </span>
    </div>
  )
}

export default BodyHero
