import { useState } from 'react'
import marsWebp from '../assets/bodies/mars-1600.webp'
import marsPng from '../assets/bodies/mars-1600.png'
import moonWebp from '../assets/bodies/moon-1600.webp'
import moonPng from '../assets/bodies/moon-1600.png'

// Inline ~24px blurred WebP previews — instant first paint, no network round-trip (IMG-02).
// Generated by Plan 07-01; full strings live in 07-01-LQIP.md.
const LQIP = {
  mars: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoYAA0APzmGu1QvKSYjMAgB4CcJZAAAWllKf/cjk4VYAP7r4tTrGiZGpIQ/WRMVtC1vKDp8iJnvfL3VPc/n+d0o+LiWgYuD01Smrp9EQAA=',
  moon: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAA0APzmIulQvKSWjMAgB4CcJZwAAWqAUaPVcJQ2q/oAA/uvgWk+A0FJoB4InLlPxK9PUvSc8V3vbRxO5pHj84p3KYFuSJ3b1CAAA',
}

const HERO_ASSETS = {
  mars: { webp: marsWebp, png: marsPng, alt: "Mars — artist's impression" },
  moon: { webp: moonWebp, png: moonPng, alt: "Moon — artist's impression" },
}

function BodyHero({ activeTab }) {
  const [imgLoaded, setImgLoaded] = useState(false)
  const asset = HERO_ASSETS[activeTab]
  const lqip = LQIP[activeTab]

  return (
    <div className="relative w-full aspect-[16/7] rounded-lg overflow-hidden mb-4">
      {/* LQIP layer — instant blur-up, fades out when full image loads */}
      <div
        className="absolute inset-0 bg-cover bg-center transition-opacity duration-300"
        style={{
          backgroundImage: `url(${lqip})`,
          filter: 'blur(8px)',
          opacity: imgLoaded ? 0 : 1,
        }}
      />

      {/* Full-res hero — keyed on activeTab so the swap remounts (resets imgLoaded for the new body) */}
      <picture key={activeTab}>
        <source srcSet={asset.webp} type="image/webp" />
        <img
          src={asset.png}
          alt={asset.alt}
          width={1600}
          height={700}
          loading="eager"
          onLoad={() => setImgLoaded(true)}
          className="absolute inset-0 h-full w-full object-cover object-center"
        />
      </picture>

      {/* Bottom vignette — soft handoff into the data panel below */}
      <div
        className="absolute inset-x-0 bottom-0 h-1/3"
        style={{ background: 'linear-gradient(to top, #020617 0%, transparent 100%)' }}
      />

      {/* Artist's impression honesty label (D-01) — bottom-right dark pill */}
      <span
        className="absolute bottom-2 right-2 rounded bg-black/50 px-2 py-1 text-xs text-white"
        aria-label="This is an artist's impression, not a photograph"
      >
        Artist's impression
      </span>
    </div>
  )
}

export default BodyHero
